(*Test Cases for Joseph Acost and Timothy Cohen PA1*)

(*Test 1*)
with8with lambda x (* let (* lambda *) fun *) 
, @ , ( ) & 2  ! . isNil with 7 if then else lambda 86

(*Test 2*)
+ - asdfads234 * / 2345 ( ) & | = <> < > >= <= 
fun func "fun" , comma in

(*Test 3*)
with8with with 8 with (*with (*8*) with*)
,, ",, comma comma ,,"

(*Test 4*)
500f 500 "500" "500f" (*500 500(*(*5*)*)*)
if then ifthen else ifelse if else lambda "lambda" lambdaa

(*Test 5*)
readString readInt print ! Nil nil . with / 
786592357034975     f0970970
#
(*this a a comment (*test that should fail*)